#%RAML 1.0
---

title: User Information
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Scopes
   content: !include docs/scopes.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  successResponse:
    responses:
      200:
        body:
          application/json:
            type: <<responseSchema>>
            examples:
              example-1:
                value: <<successExample>>

/userinfo:
  /:
    get:
      displayName: Get user information
      description: Retrieves OpenID Connect compliant information about the signed-in user
      is:
        - headers.acceptHeader
      (annotations.scope): "openid"
      securedBy: [ sec.oauth_2_0: { scopes: [ "openid" ] } ]
      responses:
        200:
          body:
            application/json:
              type: !include schemas/userinfo.json
              examples:
                example-1:
                  value: !include examples/get-user-info-example-1.json
        403:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Forbidden operation
                  value:
                    code: FORBIDDEN
